### ISSUE TITLE
errors when using https mode

### ISSUE THREAD

**Issue by amgads** [jenshadlich/S3-Performance-Test#10]
I have been using the tool with "http" mode for more than a year now.
Trying the tool with "https" mode -- I believe there’s an issue with the tool. After creating a bucket with the s3cmd, I tried to upload few objects, It failed with the following error:

# java -jar /usr/lib/STObench/s3pt/s3pt.jar --bucketName s3://rookbucket --endpointUrl rook-ceph-rgw-rook-ceph-store.rook-ceph.svc --accessKey PJY3OUNC8JHD8HSV9YBH --secretKey BPK9eoE10JO3rhCT4yJpOD6KWFa4DxZ5VeGRhkg5 --operation UPLOAD --size 10 -n 10 -t 1 --signerOverride S3Signer

2020-03-10 16:07:46,672 INFO [pool-1-thread-1] de.jeha.s3pt.operations.Upload Upload: n=10, size=10 byte
2020-03-10 16:07:46,996 ERROR [main] de.jeha.s3pt.S3PerformanceTest An error occurred
java.util.concurrent.ExecutionException: com.amazonaws.services.s3.model.AmazonS3Exception: null (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: tx0000000000000000037f9-005e67bb52-165f-rook-ceph-store), S3 Extended Request ID: 165f-rook-ceph-store-rook-ceph-store
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at de.jeha.s3pt.S3PerformanceTest.call(S3PerformanceTest.java:99)
        at de.jeha.s3pt.Main.run(Main.java:124)
        at de.jeha.s3pt.Main.main(Main.java:76)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: null (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: tx0000000000000000037f9-005e67bb52-165f-rook-ceph-store)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1387)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:940)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:715)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:466)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:427)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:376)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4039)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1583)
        at de.jeha.s3pt.operations.Upload.call(Upload.java:52)
        at de.jeha.s3pt.operations.Upload.call(Upload.java:18)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-03-10 16:07:46,997 INFO [main] de.jeha.s3pt.S3PerformanceTest Done
2020-03-10 16:07:46,997 INFO [main] de.jeha.s3pt.Main Total time = 1007 ms
bash-4.2# java -jar /usr/lib/STObench/s3pt/s3pt.jar --bucketName s3://rookbucket --endpointUrl rook-ceph-rgw-rook-ceph-store.rook-ceph.svc --accessKey PJY3OUNC8JHD8HSV9YBH --secretKey BPK9eoE10JO3rhCT4yJpOD6KWFa4DxZ5VeGRhkg5 --operation UPLOAD --size 10 -n 1 -t 1 --signerOverride S3Signer
2020-03-10 16:15:24,125 INFO [pool-1-thread-1] de.jeha.s3pt.operations.Upload Upload: n=1, size=10 byte
2020-03-10 16:15:24,468 ERROR [main] de.jeha.s3pt.S3PerformanceTest An error occurred
java.util.concurrent.ExecutionException: com.amazonaws.services.s3.model.AmazonS3Exception: null (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: tx000000000000000003828-005e67bd1c-165f-rook-ceph-store), S3 Extended Request ID: 165f-rook-ceph-store-rook-ceph-store
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at de.jeha.s3pt.S3PerformanceTest.call(S3PerformanceTest.java:99)
        at de.jeha.s3pt.Main.run(Main.java:124)
        at de.jeha.s3pt.Main.main(Main.java:76)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: null (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: tx000000000000000003828-005e67bd1c-165f-rook-ceph-store)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1387)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:940)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:715)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:466)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:427)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:376)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4039)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1583)
        at de.jeha.s3pt.operations.Upload.call(Upload.java:52)
        at de.jeha.s3pt.operations.Upload.call(Upload.java:18)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-03-10 16:15:24,469 INFO [main] de.jeha.s3pt.S3PerformanceTest Done
2020-03-10 16:15:24,469 INFO [main] de.jeha.s3pt.Main Total time = 1052 ms

**Comment by amgads** [comment]
I figured out the issue and worked around it. Could be an enhancement, but will close the issue for now

**Comment by bmv126** [comment]
@amgads 
How did you resolve this issue ? Can you provide some inputs ?

**Comment by amgads** [comment]
The --endpointUrl only works with the IP address -- so you use --endpointUrl 10.254.188.207:443 
If you use a qualified DNS name say name:port it won't work. So I think the tool should use either to lookup.

**Comment by bmv126** [comment]
Thanks for the response. I was able to make it work after using IP instead of fqdn.

**Comment by amgads** [comment]
Glad it worked for you
