### ISSUE TITLE
AmazonS3Client.getObject method problem

### ISSUE THREAD

**Issue by chensien** [jenshadlich/S3-Performance-Test#2]
hi,I use S3-Performance-Test tool to test S3-compatible object storage systems  Ceph with radosgw, but when i download file,occurred an AmazonS3Exception, can you tell me why ?   Exception.StackTrace like :

```
Exception in thread "main" com.amazonaws.services.s3.model.AmazonS3Exception: null (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: null), S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1307)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:894)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:597)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:363)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:329)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:308)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3659)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1162)
	at com.amazonaws.services.s3.AmazonS3Client$3.getS3ObjectStream(AmazonS3Client.java:1243)
	at com.amazonaws.services.s3.internal.ServiceUtils.retryableDownloadS3ObjectToFile(ServiceUtils.java:355)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1239)
```

**Comment by jenshadlich** [comment]
Hi,
please have a look at the radosgw logs. This stacktrace does not contain any valuable information. What options did you use? You should set `--useOldS3Signer` (V2 signatures) and maybe `--usePathStyleAccess`.

**Comment by chensien** [comment]
thanks a lot. the problem haved been resolved by setting   --useOldS3Signer  (enable V2 signatures because Ceph does not support V4)
